projects/WeTek_Hub/options, projects/WeTek_Play_2/options
(ppsspp psx-rearmed glupen64 mupen64plus and mame2000)
=> Fix Wetek PLay_2 & Hub libretro cores compile

CONTRIBUTING.md
Parallels the `CONTRIBUTING.md` in OE Lakka, with a few tweaks
=> Update CONTRIBUTING.md for Lakka use

packages/network/samba/config/smb.conf
This PR mirrors the OE Lakka PR: https://github.com/libretro/Lakka/pull/628
=> add Assets SMB share as in OE Lakka

packages/libretro/atari800/package.mk
Fix [this feature request](https://forums.libretro.com/t/libreelec-based-images-for-testers/8485/82).
=> Update Atari800 core and switch it to git

projects/OdroidXU3/bootloader/boot.ini
Should fix issue #126 
[Source](https://github.com/libretro/Lakka/commit/d0a2f1ee73739819b632faa2231c0ab8ba498ca7)
=> Added video ouput to kernel boot arguments for Odroid XU(3|4)

packages/compress/zlib/package.mk
Old package 1.2.8 isn't avvibale, update to last package
=> Update Zlib to 1.2.11

distributions/Lakka/options, packages/libretro/chailove/package.mk
ChaiGame was renamed to ChaiLove to reflect better what it is.
=> Rename ChaiGame to ChaiLove V2.1

packages/libretro/chailove/package.mk
This updates the [ChaiLove](https://github.com/RobLoach/ChaiLove) package to 0.8.0.
=> chailove: update to 0.8.0

packages/libretro/beetle-pcfx/package.mk, packages/libretro/beetle-psx/package.mk, packages/libretro/beetle-saturn/package.mk, packages/libretro/bluemsx/package.mk, packages/libretro/bsnes-mercury/package.mk, packages/libretro/chailove/package.mk, packages/libretro/core-info/package.mk, packages/libretro/fbalpha/package.mk, packages/libretro/fceumm/package.mk, packages/libretro/fuse-libretro/package.mk, packages/libretro/genesis-plus-gx/package.mk, packages/libretro/glsl-shaders/package.mk, packages/libretro/imame4all/package.mk, packages/libretro/libretro-database/package.mk, packages/libretro/mame2000/package.mk, packages/libretro/mame2003-midway/package.mk, packages/libretro/mame2003/package.mk, packages/libretro/mame2010/package.mk, packages/libretro/melonds/package.mk, packages/libretro/meteor/package.mk, packages/libretro/nxengine/package.mk, packages/libretro/ppsspp/package.mk, packages/libretro/redream/package.mk, packages/libretro/retroarch-assets/package.mk, packages/libretro/retroarch-joypad-autoconfig/package.mk, packages/libretro/retroarch/package.mk, packages/libretro/sameboy/package.mk, packages/libretro/snes9x2010/package.mk
redream and sameboy needed additional changes / discussed with @Ntemis via IRC
=> update libretro cores and retroarch

packages/libretro/parallel-n64/package.mk
=> Slice: fix parallel-n64 build

packages/libretro/mupen64plus/package.mk
added Slice to case of RPi and Gamegirl
=> Slice: fix muppen64plus

packages/libretro/chailove/package.mk
- Documentation
- `math.random()` for int, float and double numbers
- Renamed `mousemove()` callback to `mousemoved()`
- `love.graphics.setDefaultFilter()` flags
=> chailove: Update to 0.13.0

distributions/Lakka/options, packages/libretro/gme/package.mk
Compilation tested for Generic x86_64 and RPi2/3 arm
=> Package Game Music Emu core

packages/linux/package.mk, projects/OdroidXU3/linux/linux.arm.conf, projects/OdroidXU3/patches/linux/linux-usbhid-quircks.patch, projects/OdroidXU3/patches/linux/linux-wiimote-abs-not-hat.patch
Add atmega quirks(xin-mo etc) and fix wiimote
=> XU[34]:Update kernel to 4.14.16 LTS

distributions/Lakka/options, packages/libretro/freeintv/package.mk
see https://github.com/libretro/Lakka-LibreELEC/issues/342
Successful build tests on all supported platforms.
Did not test the core - I don't have the required BIOS and ROM files.
=> new core: FreeIntv - Mattel Invtellivision

packages/libretro/sameboy/package.mk
tested with latest canary builds.
=> sameboy: PKG_BUILD is not needed

packages/libretro/desmume/package.mk
=> desmume: fix/update url

packages/libretro/retroarch/patches/retroarch-01-generic-drm-fix.patch
Fixes https://github.com/libretro/Lakka-LibreELEC/issues/429
Thanks @gouchi and @twinaphex
=> Fix Generic DRM bug

packages/libretro/retroarch/package.mk
https://github.com/libretro/RetroArch/releases
Signed-off-by: Ntemis <ierokipides.dem@gmail.com>
=> retroarch: Update RetroArch to 1.7.2

packages/devel/cmake/package.mk, packages/devel/cmake/patches/cmake-002-fix-strerror.patch
- Update CMake to version 3.10.
- Fix compilation issue about strerror with this [patch](https://github.com/curl/curl/pull/2443/files).
=> cmake : Update to version 3.10.0

packages/libretro/4do/package.mk, packages/libretro/beetle-saturn/package.mk, packages/libretro/beetle-supergrafx/package.mk, packages/libretro/chailove/package.mk, packages/libretro/core-info/package.mk, packages/libretro/fbalpha/package.mk, packages/libretro/freeintv/package.mk, packages/libretro/genesis-plus-gx/package.mk, packages/libretro/glsl-shaders/package.mk, packages/libretro/gpsp/package.mk, packages/libretro/libretro-database/package.mk, packages/libretro/mame2003-plus/package.mk, packages/libretro/mgba/package.mk, packages/libretro/mrboom/package.mk, packages/libretro/o2em/package.mk, packages/libretro/prboom/package.mk, packages/libretro/retroarch-assets/package.mk, packages/libretro/retroarch-joypad-autoconfig/package.mk, packages/libretro/retroarch/package.mk, packages/libretro/snes9x2010/package.mk, packages/libretro/virtualjaguar/package.mk
https://github.com/libretro/RetroArch/releases
=> Update Retroarch & Cores to be on par with V1.7.3 stable

distributions/Lakka/options, packages/libretro/mesen/package.mk
- Fix #514 
- Compilation tested for x84_64 and RPi2
=> mesen : add mesen libretro core

packages/libretro/reicast/package.mk, packages/libretro/reicast/patches/reicast-01-buildfix.patch
This needs to be tested
i386 build broken
=> Update reicast, fix compilation for ARM

packages/linux/package.mk, projects/OdroidXU3/linux/linux.arm.conf
Benefits: https://github.com/hardkernel/linux/pull/363
=> XU[34] Update kernel to 4.14.73 LTS

scripts/mkimage
Allow boot from USB and SD for Raspberry Pi devices that support USB boot.
Resolve #611
=> Create cmdline.txt using LABEL for boot and disk

packages/libretro/retroarch/patches/retroarch-02-graceful-shutdown-reboot-hack.patch
fixes #620 and possible filesystem corruptions
=> retroarch: patch (hack) to allow graceful shutdown

config/path, packages/devel/glib/package.mk, packages/lang/llvm/package.mk, packages/tools/qemu/patches/qemu-01-memfd-fix-configure-test.patch
these are fixes I had to make in order to make the builds work on ubuntu 18.04.02 LTS.
it solves #598, which makes #634 and #645 obsolete.
=> Buildfixes

packages/libretro/mupen64plus/package.mk
+ Generic: added dynarec flags
+ OdroidC1: fixed BOARD flag
+ ROCK960: removed (same as default case)
=> mupen64plus: build flag changes

packages/libretro/mame2010/package.mk
=> mame2010: adding aarch64 support

packages/libretro/beetle-psx/package.mk, packages/libretro/beetle-psx/patches/beetle-psx-01-verbose-makefile.patch
compiled and runs on switch (albeit a bit slow)
@mlnlbrt if you can take a look and make sure this still works for Generic_VK
=> beetle-psx: auto-detect options for opengl, vulkan, or both

packages/libretro/genesis-plus-gx/package.mk, packages/libretro/genesis-plus-gx/patches/genesis-plus-gx-01-no-optimization.patch
=> genesis-plus-gx: fix segfault at runtime for aarch64

packages/libretro/ppsspp/package.mk, packages/libretro/ppsspp/patches/ppsspp-arm-arm64-fix.patch
=> ppsspp: remove platform target from makefile patch

packages/libretro/retroarch/package.mk
=> enable unit for overlays

distributions/Lakka/options, packages/libretro/fbneo/package.mk, packages/libretro/libretro-database/package.mk, tools/mkpkg/mkpkg_fbneo
compiles and runs great on switch
=> fbneo: replaces fbalpha

projects/OdroidXU3/filesystem/etc/asound.conf, projects/OdroidXU3/filesystem/etc/modules.conf
- https://github.com/libretro/Lakka-LibreELEC/issues/647
- https://github.com/libretro/Lakka-LibreELEC/issues/627
=> XU4: Fixes for

distributions/Lakka/options, packages/libretro/kronos/package.mk
=> kronos: new core

distributions/Lakka/options, packages/libretro/yabasanshiro/package.mk, projects/Allwinner/options, projects/Gamegirl/options, projects/OdroidC1/options, projects/Odroid_C2/options, projects/RPi/options, projects/RPi2/options, projects/Rockchip/options, projects/S805/options, projects/S8X2/options, projects/S905/options, projects/S912/options, projects/Slice/options, projects/Slice3/options, projects/WeTek_Core/options, projects/WeTek_Hub/options, projects/WeTek_Play/options, projects/WeTek_Play_2/options, projects/imx6/options
compiles and runs on switch. has a problem where the games freeze every few minutes. haven't yet diagnosed.
=> yabasanshiro: new core

packages/libretro/dolphin/package.mk
=> dolphin: add aarch64 support and build patch

distributions/Lakka/options
tested, compiles and runs on switch
=> mame2010: add it to the core list

packages/libretro/dosbox-svn/package.mk
Since radius took his GitHub repo down
=> dosbox-svn: use libretro mirror

packages/libretro/core-info/package.mk, packages/libretro/libretro-database/package.mk
RE: https://github.com/libretro/Lakka-LibreELEC/pull/699
=> Update Database and Core Info files

distributions/Lakka/options, packages/libretro/tic80/package.mk
Built and ran correctly on my Raspberry Pi, but would always love more testing!
=> Add TIC-80 core

projects/Allwinner/patches/linux/0001-hdmi-sound-improvements.patch
due to linux version change this two hunks failed:
- first one already in upstream
- second one did not match the lines after the changes
=> Allwinner: patch a patch

CONTRIBUTING.md, README.md
also removed in README the original text, which is now included in
CONTRIBUTING, but with more details
=> Update CONTRIBUTING with good practices

pkg_all.sh
- build_folder based on OS_VERSION/LIBREELEC_VERSION/IGNORE_VERSION
- added output before/after activity
- cleanup
*Note for buildbot: [DNB] no changes to the build system/packages*
=> pkg_all.sh: enhancements

packages/libretro/kronos/package.mk, packages/libretro/mgba/package.mk, packages/libretro/play/package.mk
kronos: add OPENGL/ES dependency
mgba: set PKG_TOOLCHAIN
play: add glu dependency
=> Fix some libretro packages

packages/tools/dtc/package.mk, packages/tools/u-boot/package.mk, projects/Allwinner/bootloader/firmware, projects/Allwinner/devices/A64/options, projects/Allwinner/devices/H6/options, projects/Amlogic/options, projects/Rockchip/options, scripts/uboot_helper
these commits are cherry-picked from LibreELEC.tv/master in order to allow image build of Qualcomm Dragonboard.
=> add dragonboard to uboot_helper

distributions/Lakka/options, packages/libretro/gearsystem/package.mk
Hi,
just tested on generic x64.
=> gearsystem : add gearsystem libretro core

distributions/Lakka/options, packages/libretro/gearsystem/package.mk, packages/libretro/mesen-s/package.mk
- mesen-s core (#740)
- gearsystem core (#742)
- playlist names/cores (#748)
=> Lakka-LE9.2: backports from master

projects/RPi2/boards/RPi4/linux/linux.arm.conf
=> RPi4: fix CMDLINE

CHANGELOG, config/noobs/os.json, scripts/image
It now boots correctly. 
The distribution is also now listed as "Lakka" instead of "Lakka_RPI2" (for all RPi versions)
=> Fix RPi4 NOOBS install

config/noobs/os.json, distributions/Lakka/options, scripts/image
PINN is a NOOBS variant with more stuff in it. This adds the fields necessary for Lakka to be visible in the PINN repository.
=> NOOBS: add PINN specific values

packages/libretro/dosbox-svn/package.mk, packages/libretro/picodrive/package.mk, packages/libretro/play/package.mk, packages/libretro/ppsspp/package.mk, packages/libretro/sameboy/package.mk, packages/libretro/snes9x/package.mk
This only fixes cores that have been rebased / broken since the last time the LE9 branch was updated. Fresh builds should work again !
=> Minor libretro update

projects/Rockchip/devices/OdroidGoAdvance/options, projects/Rockchip/devices/OdroidGoAdvance/packages/odroidgo2-utils/package.mk, projects/Rockchip/devices/OdroidGoAdvance/packages/odroidgo2-utils/sources/headphone_sense.sh, projects/Rockchip/devices/OdroidGoAdvance/packages/odroidgo2-utils/system.d/odroidgoa-utils.service
This enables audio on boot and redirects it to headphones or speakers automatically.
=> Enable audio and headphone sensing

packages/libretro/fbneo/package.mk, packages/libretro/flycast/package.mk, packages/libretro/flycast/patches/flycast-01-buildfix.patch, packages/libretro/pcsx_rearmed/package.mk, packages/libretro/scummvm/package.mk, packages/libretro/scummvm/patches/scummvm-01-add-oga-platform.patch, packages/libretro/snes9x/package.mk, packages/libretro/snes9x2010/package.mk, packages/libretro/snes9x2010/patches/snes9x2010-add-oga.patch
Optimize the following cores for the Odroid Go Advance:
Fbneo
Scummvm
Flycast
PCSX_rearmed
Snes9x
Snes9x_2010
=> Use proper flags for OdroidGoAdvance a35

distributions/Lakka/options, packages/libretro/neocd/package.mk
- Compile fine on x86 and arm.
=> neocd : add neocd libretro core

.dockerignore, .gitignore, Dockerfile
Updated and adapted from https://github.com/libretro/Lakka-LibreELEC/tree/Lakka-2.3.2
=> Added support for building Lakka in a docker container

distributions/Lakka/options, packages/libretro/mame2015/package.mk
2014 became 2015 so updated and enabled
=> mame(2014/2015) enable

config/graphic
Change option imx to kmsro.
https://lists.freedesktop.org/archives/mesa-dev/2019-January/214067.html
=> Fix graphic drivers options for Vivante GPU

distributions/Lakka/options
Verified compilation on RPi.arm
=> enable vba-next

distributions/Lakka/options, packages/libretro/pokemini/package.mk
Had to add URL and define toolchain to get it to work.
=> [Pokemini] Fixup build and enable

packages/libretro/retroarch/patches/retroarch-04-vc-egl-fix.patch
Got implicit declaration compile errors on RPi projects. Moved the function and made it compile.
=> add patch to fix retroarch videocore compile

packages/libretro/duckstation/package.mk
- I tested it and it is working correctly on Lakka now.
=> duckstation : Update to the latest commit

packages/libretro/uae4arm/package.mk
Tested on a rpi2 and it's ok. The core update make it more usable.
=> Update uae4arm to it's latest version

packages/sysutils/systemd/patches/systemd-0004-core-set-fs.file-max-sysctl-to-LONG_MAX.patch
https://github.com/systemd/systemd/issues/12803
=> systemd: fix bump fs.file-max

packages/libretro/melonds/package.mk
~~This will fail to build as is. It will need updating when the melonds change is merged.~~
Fixed
=> rpi4-aarch64: add melonds

packages/libretro/uae4arm/package.mk
Game compatibility is better with this version.
=> Switch to more updated uae4arm upstream repo

packages/compress/cpio/patches/fix-gcc10-globals.patch
Adding a patch from upstream (641d3f4)
=> Fix cpio GCC10 build

packages/lang/llvm/patches/0999-fix-gcc10-includes.patch
As per https://reviews.llvm.org/D64937
=> Fix includes in llvm for gcc 10 builds

packages/libretro/beetle-pce/package.mk
=> Beetle-Pce Update

projects/NXP/devices/iMX6/bootloader/mkimage, projects/NXP/devices/iMX6/bootloader/release, projects/NXP/devices/iMX6/bootloader/scripts/boot.scr.src, projects/NXP/devices/iMX6/options, scripts/uboot_helper
This will reduce images for Wandboards from 4 to 1 and add 2 images for CuBox-i and Udoo boards.
=> iMX6: make one image for all Wandboards, add CuBox-i and Udoo

packages/linux/patches/odroidgoA-4.4/linux-990-rg351p-rumble.patch
Also bumped the period to a bigger value since gives a bit more rumble effect I think.
=> Fixing Rumble driver crashes due to race condition

packages/libretro/core-info/package.mk, packages/libretro/uae4arm/package.mk
=> Add CD32 support in uae4arm

distributions/Lakka/options, packages/libretro/lowres-nx/package.mk
- To be merged when we [update libretro cores](https://github.com/libretro/Lakka-LibreELEC/pull/1122).
- Tested on x86_64 and arm
=> lowres-nx : Add lowres-nx to libretro cores

packages/libretro/retroarch/patches/retroarch-20-brightness.patch
Causes many issues including crashes and funny lang changes
=> Fix regression introduced in brightness patch

packages/libretro/core-info/package.mk, packages/libretro/uae4arm/package.mk
=> uae4arm: add support of ipf files, CD32 and whdload install though .lha

packages/libretro/fbneo/package.mk, packages/libretro/gpsp/package.mk
* Update FBNeo for Sega 32 support
* Update gpsp for the ARM work that @davidgfnet did
=> Fbneo and gpsp Update

packages/linux/patches/odroidgoA-4.4/linux-998-rg351v-dts.patch, projects/Rockchip/bootloader/rg351v.ini, projects/Rockchip/devices/OdroidGoAdvance/options, scripts/uboot_helper
Unfortunately there's no easy way to choose DTBs at u-boot time, so
keepting a separated image for now.
=> Add support for RG350V

packages/graphics/mesa/package.mk, packages/libretro/beetle-psx/package.mk, packages/libretro/retroarch/package.mk, projects/Generic/options, projects/Generic/patches/vulkan-loader/vulkan-loader-asm_offset_executable.patch, projects/RPi/options
minor changes also to RPi - changed VULKAN to vulkan-loader,
vulkan-headers are pulled in as dependency of vulkan-loader
=> Generic: enable vulkan, increase partition size

packages/libretro/retroarch/package.mk, packages/sysutils/eventservice/package.mk, packages/sysutils/eventservice/sources/Makefile, packages/sysutils/eventservice/sources/spkeys-service.c, projects/Rockchip/devices/OdroidGoAdvance/options, projects/Rockchip/devices/OdroidGoAdvance/packages/odroidgoa-volkeys/package.mk, projects/Rockchip/devices/OdroidGoAdvance/packages/odroidgoa-volkeys/system.d/odroidgoa-volkeys.service
This relies on a new feature just added to Retroarch and offers a more generic mechanism to interact with it.
=> Add volume key support to OGA and RG351V

packages/libretro/retroarch/package.mk
gravitone reported on discord that these were missing
=> rpi4: enable slang shaders

packages/tools/bcm2835-bootloader/package.mk, packages/tools/bcm2835-bootloader/release
This makes all copies of the file identical. This hopefully fixes #1242
=> Move bootloader config patch for consistency

distributions/Lakka/options
- It should compile now.
- Fix #1133
=> stella : Add stella to Libretro cores

projects/OdroidXU3/packages/libgbm/package.mk, projects/OdroidXU3/packages/odroidxu3-mali/package.mk
Install GBM header to fix Duckstation build.
=> OdroidXU3: add libgbm package

distributions/Lakka/options, packages/libretro/mame2015/package.mk
This does build but is *not tested*
=> rpi4-aarch64: fix mame2015 build

distributions/Lakka/options, packages/libretro/beetle-supafaust/package.mk
- Add beetle-supafaust for arm platform
=> beetle-supafaust: Add beetle-supafaust to Libretro cores

packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk, packages/libretro/uae4arm/package.mk
=> Add support of aarch64 for uae4arm

build_all.sh
=> [LakkaV3] build_all: drop rpi4.arm, keep .tar files, create 7z for switch

packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk
=> mpg123: create shared objects for Lakka

packages/sysutils/systemd/package.mk
=> rpi: change HandlePowerKey action to poweroff

packages/libretro/retroarch/package.mk, packages/x11/lib/libXcomposite/package.mk, packages/x11/lib/libXdamage/package.mk, packages/x11/lib/libXfixes/package.mk, packages/x11/lib/libXfont2/package.mk, packages/x11/lib/libXi/package.mk, packages/x11/lib/libXinerama/package.mk, packages/x11/lib/libXmu/package.mk, packages/x11/lib/libXrender/package.mk, packages/x11/lib/libXt/package.mk, packages/x11/lib/libXtst/package.mk, packages/x11/lib/libXxf86vm/package.mk, packages/x11/lib/libxcb/package.mk, packages/x11/lib/libxkbfile/package.mk, packages/x11/lib/libxshmfence/package.mk, projects/L4T/devices/Switch/packages/switch-bootloader/assets/boot.txt, projects/L4T/packages/tegra-bsp/package.mk
This commit fixes the vulkan renderer on L4T platform builds(Nintendo Switch)
=> L4T: Fix Vulkan Renderer

packages/linux-drivers/bcm_sta/patches/bcm_sta-0012-kernel-4.14-i386.patch, packages/linux-drivers/bcm_sta/patches/bcm_sta-0012-kernel-4.14.patch
Patch for bcm_sta from LE upstream.
=> bcm_sta: fix kernel_read() parameters

projects/L4T/packages/tegra-bsp/package.mk
All the code contributions are submitted in the form of Pull Requests. Team members should also use Pull Requests except in case of emergency.
A good PR is:
* Atomic, changes as less things as possible
* Well named
* Well described
* Tested locally by the sender (on real hardware)
* Doesn't break other projects (you have to build all of them locally)
* Idealy doesn't contain merge messages (you can pull --rebase if necessary)
* Doesn't mix important changes with massive reindentation (send two separate PRs)
* Doesn't introduce too much changes that would make merging upstream difficult
PRs will be reviewed by the core team. The project leader have the final word on merging a PR or not, but all the core team members are invited to do code reviews.
PRs should be merged using the *Squash and …
=> l4t : Fix audio regression from rework of tegra-bsp

distributions/Lakka/options
=> rpi4: re-enable openlara

distributions/Lakka/options
also disable beetle-saturn for RPi / GPICase, as it was disabled in the
past
=> add back cores that were removed due to space

packages/libretro/flycast/package.mk, projects/L4T/options
* enables flycast on switch
* defines build params for L4T builds
=> flycast: enable and fix build for switch

packages/lang/Python2/package.mk, packages/libretro/retroarch/patches/retroarch-08-get-better-battery-stats-on-sysfs-nodes.patch, packages/sysutils/systemd/patches/systemd-0901-shared-machine-image-avoid-passing-NULL-to-log_debug_errno.patch, packages/sysutils/systemd/patches/systemd-0902-tree-wide-Workaround-Wnonnull-GCC-bug.patch, projects/L4T/options
All the code contributions are submitted in the form of Pull Requests. Team members should also use Pull Requests except in case of emergency.
A good PR is:
* Atomic, changes as less things as possible
* Well named
* Well described
* Tested locally by the sender (on real hardware)
* Doesn't break other projects (you have to build all of them locally)
* Idealy doesn't contain merge messages (you can pull --rebase if necessary)
* Doesn't mix important changes with massive reindentation (send two separate PRs)
* Doesn't introduce too much changes that would make merging upstream difficult
PRs will be reviewed by the core team. The project leader have the final word on merging a PR or not, but all the core team members are invited to do code reviews.
PRs should be merged using the *Squash and …
=> Fix cflag issues, and add retroarch patch for better sysfs battery handling

packages/lang/Python2/package.mk, packages/libretro/retroarch/package.mk, projects/L4T/packages/tegra-bsp/package.mk
added space separation between operator and operands (i.e. `[ "$VAR"="value" ]` --> `[ "$VAR" = "value" ]`, rest is cosmetics
=> Fix tests in some packages

packages/libretro/pcsx_rearmed/package.mk, projects/L4T/devices/Switch/options
- L4T/switch:
- ppsspp: enable vulkan
- beetle-psx: enable vulkan
- pcsx-rearmed:
- switch to unai rendering
- disable lightrec
=> Switch & pcsx-rearmed

distributions/Lakka/options, packages/libretro/mupen64plus_next/package.mk, packages/libretro/parallel-n64/package.mk
(credit to metchebe for the options)
=> rpi3-aarch64: re-enable n64 cores

distributions/Lakka/options, packages/libretro/melonds/package.mk
this enables MelonDS for aarch64 devices and enables JIT for switch
=> L4T: enable melonds

distributions/Lakka/options, packages/libretro/np2kai/package.mk
=> np2kai: Add np2kai to Libretro cores

packages/sysutils/udevil/udev.d/95-udevil-mount.rules
Add forgotten commits from LE upstream to fix issue #1377
buildbot: [dnb]
=> Include /dev/nvme* for automounting m.2 devices

config/graphic, packages/graphics/libdrm/package.mk, packages/graphics/mesa/package.mk, packages/libretro/pcsx2/package.mk
=> Update mesa to 21.2.1 and enable crocus

packages/libretro/retroarch/package.mk
I think this works better on small screens
=> RPi4-PiBoyDmg: change default menu to rgui

packages/libretro/retroarch/package.mk
Changed to look a bit more hip
=> RPi4-RetroDreamer/RPi4-PiBoyDmg: change default menu to ozone

packages/libretro/flycast/package.mk
This needs another fix in the CMakeLists.txt which I have submitted upstream.
=> flycast: fix opengles compile

packages/libretro/gpsp/package.mk
Update gpsp and use native dynarec for arm64
=> Bump gpsp version

packages/libretro/flycast/package.mk
Update version to the commit which fixes a typo preventing the package compilation
=> flycast: update to e61951a

packages/libretro/play/package.mk
This change opportunity was brought up by @gouchi over at https://github.com/libretro/Lakka-LibreELEC/pull/1575 .
=>  libretro: play: Update to a later version

distributions/Lakka/options, packages/libretro/core-info/package.mk, packages/libretro/jumpnbump/package.mk
```
jumpnbump: add jumpnbump core
```
=> jumpnbump : add  jumpnbump to Libretro cores

distributions/Lakka/options, packages/lakka/libretro_cores/jumpnbump/package.mk, packages/lakka/retroarch_base/core_info/package.mk
=> jumpnbump : add core (Lakka-v4.x)

packages/libretro/libretro-database/package.mk
=> database: bump git ref to latest

packages/libretro/retroarch/package.mk
a change in retroarch between retroarch v1.9.13.2 and v1.9.14 changes how wifi drivers are compiled in retroarch
adding HAVE_WIFI fix the issue
=> restore WIFI drivers

packages/libretro/chailove/package.mk
This update comes with some Makefile updates.
=> chailove: Update to 1.2.0

packages/libretro/jumpnbump/package.mk
last one, but I had to add option to disable the annoying flies
=> jumpnbump : update
