packages/lang/llvm/package.mk
=> Enable LLVM for i386

projects/WeTek_Hub/filesystem/etc/asound.conf, projects/WeTek_Hub/initramfs/platform_init, projects/WeTek_Play_2/filesystem/etc/asound.conf, projects/WeTek_Play_2/initramfs/platform_init
Fix the following issues on WeTek Hub and WeTek Play 2:
* Garbled screen output for resolutions other than 1920x1080.
* No sound.
=> WeTek Hub and WeTek Play 2 fixes

packages/libretro/retroarch/udev.d/99-nv-shield-controller.rules
See libretro/Lakka#379. Update udev rules to use the pre-2017 Shield Controller.
=> Rules for Shield Controller

packages/libretro/retroarch/package.mk
I dug a little deeper and I found a solution to issue #113
packages/libretro/retroarch/package.mk was missing the correct $OPENGLES param for the GPU on a Cubox.
"imx-gpu-viv" is the correct string in this case.
Maybe there should be a check here that informs someone that $OPENGLES is set to an unknown parameter?
=> Fix for Issue 113 [Compiling Lakka for Cubox fails @ Building Retroarch]

packages/network/samba/config/smb.conf
This PR is inspired by a thread in the forums, where a Lakka user asked for help deleting a remapping file.
It seems like it makes some sense to share this folder as well, but I will leave that up to the Lakka team to decide! Here's the thread:
https://forums.libretro.com/t/how-to-delete-a-core-game-remapping-file-lakka/10977
=> add samba share for the core/game remapping folder

packages/libretro/libretro-database/package.mk, packages/libretro/retroarch-assets/package.mk, packages/libretro/retroarch-joypad-autoconfig/package.mk
**DONT MERGE YET**
This fixes libretro-database, retroarch-assets and retroarch-joypad-autoconfig. Testing still.
=> Update to use pre_makeinstall_target()

packages/libretro/retroarch-joypad-autoconfig/package.mk
Brings in the needed Makefile and configure files.
=> retroarch-joypad-autoconfig: update to e317703

packages/libretro/lutro/package.mk
Also, let Lutro decide whether or not it wants LuaJIT. Regarding https://github.com/libretro/libretro-lutro/issues/113 .
=> lutro: update to 101ba08

packages/libretro/chaigame/package.mk
This update removes the use of the SDL/PhysFS link file usage. It compiles SDL and PhysFS directly from within the parent Makefile.
=> chaigame: Compile SDL and PhysFS directly

build_all.sh
The ROCK64 image builds and runs stable enough for use. I added it to the build_all.sh
=> Add RockChip device ROCK64 to build_all.sh

libretro_update.sh
corrected libretro_update.sh script to skip packages that don't have PKG_VERSION or PKG_SITE defined in package.mk.
substituted "source $f" with cat $f | sed .., as "source $f" tried to execute "foo" when "foo" was used in form of "X=$(foo bar)"
for example you have output like:
get_build_dir: command not found
when sourcing packages/libretro/citra/package.mk
-vudiq
=> safeguarding libretro_update.sh

scripts/unpack
when using PKG_GIT_URL and no PKG_URL, scripts/get exits with 0 (PKG_URL is empty) and hence no $SOURCES/$1 folder exists. So enhancing the condition in scripts/build with PKG_GIT_URL check - if not empty, continue with the unpack.
Please test, my daily builds are running, cannot test on my side.
Affected citra when building from clean repository. This should fix it.
=> fix: sources/unpack - when using PKG_GIT_URL

CONTRIBUTING.md
Having a standard commit message format allows the commit history to be easily read.
```
package-name: update something on the package
```
=> Contributing: Commit message format

packages/libretro/gearboy/package.mk
Tested only build, not the core behavior / urgent fix for being able to build.
=> gearboy: bump version to latest, 6b69f16 does not exist

packages/libretro/retroarch/patches/retroarch-01-xkb-fix.patch
Tested on RPi3. The diff is straightforward.
Fixes #238
Fixes #239
=> retroarch: Patch to fix keyboard typing

.dockerignore, Dockerfile
On OSX, I use it this way:
docker build -t lakka .
docker run -it -v /Users/kivutar/Lakka-LibreELEC:/root lakka
This will build Generic.x86_64 and the build and source folders will be persistent.
You can also pass all the usual env vars and target:
docker run -ti -v /Users/kivutar/Lakka-LibreELEC:/root -e PROJECT=RPi2 -e ARCH=arm lakka make image
=> Add dockerfile to build lakka anywhere

projects/S905/filesystem/usr/share/bootloader/update.sh
@ToKe79 reported an issue when updating Lakka on S905:
> I had funny issue while I was bisecting the keyboard issue - I put a .img.gz file to /storage/.update/ on the SD card (so I do not have to burn the image and wait for /storage formatting) and it relabeled the partitions to LIBREELEC and LIBREELEC_DISK
> so I could not boot :)
=> Fix S905 update

packages/libretro/retroarch/package.mk
This has changed in RetroArch - the `xmb_show_*` do not have any effect, the playlists are shown and in `Settings` -> `User Interface` -> `Views` these options are in on position. After changing these to `off` and saving config, found these new variables.
Also noticed that
```
xmb_theme = 3
xmb_menu_color_theme = 9
```
is probably ignored, as in the saved config file was following:
```
xmb_theme = "0"
xmb_menu_color_theme = "4"
```
I did not make any other changes to the settings besides the above.
=> retroarch: xmb_show_* renamed to content_show_*

Makefile
This change allows doing clean and distclean only for specific PROJECT or DEVICE, e.g. `PROJECT=RPi2 make clean` will clean (.stamps and *) only in RPi2 build folder.
=> Makefile: clean only specific BUILD_DIRS

packages/libretro/beetle-psx/package.mk, projects/Rockchip/devices/MiQi/options, projects/Rockchip/devices/TinkerBoard/options
see https://github.com/libretro/Lakka-LibreELEC/issues/378 - Rockchip is not getting vulkan support (anytime soon at least)
=> Rockchip: MiQi & TinkerBoard: remove vulkan-loader

pkg_all.sh
This script is useful if you want to build package for all targets (e.g. test if version change does not introduce build errors) or to clean a certain package on all targets (e.g. if you want to make sure that the package is rebuilt on next release/nightly build).
Usage examples:
```
./pkg_all.sh build retroarch
./pkg_all.sh clean retroarch
```
=> pkg_all.sh: build/clean a package for all targets

packages/libretro/sameboy/package.mk
bumped the version due to:
```
error: pathspec 'a5e6868' did not match any file(s) known to git.
```
=> sameboy: bump version

packages/libretro/sameboy/package.mk
The previous commit id was not found.
I tested that it still build on PC and RPi
=> Fix sameboy

packages/libretro/mame2003-plus/package.mk
1) the original package uses tarball, all other libretro packages of Lakka use git.
2) removed redundant post_unpack() - is cloned into correct folder
However does not build (Generic, S905, RPi)
I will test newer versions and commit after success to this PR.
=> [WIP] mame2003-plus: switch to git

packages/libretro/chailove/package.mk
ChaiLove 0.20.1 comes with a few updates since 0.18.0...
- No Game demo screen
- Version mismatch checking
- `love.data.hash()`
- `love.system.getUsername()`
- Better memory usage
- Fixed compilation warnings
=> chailove: Update to 0.20.1

projects/S905/filesystem/usr/share/bttty.conf
This file is needed by `/lib/systemd/system/brcmfmac_sdio-firmware-aml.service` to load the bluetooth firmware.
Note: adding only to project S905 `filesystem` folder, as S912 has a symlink to S905 folder.
=> S905/S912: add missing bttty.conf

distributions/Lakka/options, packages/libretro/core-info/package.mk, packages/libretro/libretro-database/package.mk, packages/libretro/reminiscence/package.mk
Port of Gregory Montoir's Flashback emulator, running as a libretro core.
Builds test successful for every target.
Runs on Generic.x86_64. Tried to run on S912, but got only black screen. I don't have other devices available to test.
[Images](http://nightly.builds.lakka.tv/special_builds/new-reminiscence/)
=> New libretro core: REminiscence

packages/devel/make/patches/make-glibc_alloc_fix.patch
On newer Ubuntu releases, the host `make` package refused to build due to an error with `__alloca`. This patch addresses this issue.
The error is :
```
glob/libglob.a(glob.o): In function `glob_in_dir':
glob.c:(.text+0x2c1): undefined reference to `__alloca'
glob.c:(.text+0x43e): undefined reference to `__alloca'
glob.c:(.text+0x5f8): undefined reference to `__alloca'
glob.c:(.text+0x658): undefined reference to `__alloca'
glob/libglob.a(glob.o): In function `glob':
glob.c:(.text+0x95b): undefined reference to `__alloca'
glob/libglob.a(glob.o):glob.c:(.text+0x101a): more undefined references to `__alloca' follow
collect2: error: ld returned 1 exit status
```
=> Added patch for host make

packages/libretro/chailove/package.mk
- Live updating of core options
- Mounts `/libretro/core` as the directory where the core was loaded from
- Adds `love.filesystem.getSaveDirectory()`
- Adds `love.filesystem.newFileData(contents, name)`
- Adds `love.filesystem.getExecutablePath()`
- Adds `love.filesystem.remove()`
- Fixed loading ChaiLove without active content
- Added a global `require()` function to load modules ([#308](https://github.com/libretro/libretro-chailove/pull/308))
- Added OEM-102 key support (sometimes `\` on EUR keyboard) ([#309](https://github.com/libretro/libretro-chailove/pull/309))
- Fix Windows build
- Fix Android build ([#305](https://github.com/libretro/libretro-chailove/issues/305))
- By [@bparker06](https://github.com/bparker06)
=> chailove: Update to ChaiLove 0.26.0

packages/libretro/sameboy/package.mk
When we update sameboy, we have to make sure we're referencing the latest commit from `buildbot`.
=> sameboy: Update Sameboy

distributions/Lakka/options
addresses #536 
removed only from the LIBRETRO_CORES list, the package is still there
=> redream: remove core from the list of Lakka cores

config/path, scripts/extract, scripts/get, scripts/unpack
It happens quite often that some libretro repositories lose some history and subsequent builds fail, as cloned repositories are used instead of archive/tarball. As for many libretro packages it is better to have a cloned repository for the build (e.g. to have correct GIT_VERSION in the build), this PR creates tarballs from the cloned repositories. The devs should upload the tarball(s) to the LAKKA_MIRROR after they update the libretro packages, so users download a tarball from LAKKA_MIRROR instead of cloning the individual repositories.
=> create tarballs from cloned repositories

packages/libretro/retroarch/scripts/retroarch-config, packages/sysutils/busybox/profile.d/98-busybox.conf
When libretro cores depend on shared libraries it is quite difficult to add anything to Lakka OS since root partition is a **squashfs** read-only partition. My particular issue was the **hatari_libretro.so** which was compiled without IPF support. When I recompiled it and enabled IPF, I also realized that I cannot copy the **ibcapsimage.so.4** dependency to root partition and the only was to run it would be to manually export **LD_LIBRARY_PATH** in **.profile** and run retroarch from shell, which is not acceptable. This pull request adds **/tmp/cores** overlay to **LD_LIBRARY_PATH** to facilitate installation of custom core dependencies.
=> Add /tmp/cores overlay to LD_LIBRARY_PATH

packages/libretro/chailove/package.mk
- ChaiLove now requires content to run
- Updated ChaiScript_Extras for more string methods
- Updated PhysFS
- Updated libretro-common
- Updated random to fix a gcc 7.3+ error
- Updated stb
=> chailove: Update to 0.32.0

packages/libretro/retroarch/system.d/retroarch.service
This change allows to workaround retroarch issues like the following:
```
Unable to find target for this triple (no targets are registered)
Segmentation fault (core dumped)
```
which some users are facing, so these issues can be closed (maybe some other too):
https://github.com/libretro/Lakka-LibreELEC/issues/618
https://github.com/libretro/Lakka-LibreELEC/issues/486
https://github.com/libretro/Lakka-LibreELEC/issues/322
I will document the workaround in `Hardware tips/PC` section of Lakka website later.
=> retroarch: allow to have persistent environment file

Dockerfile
Adds missing [Dependencies required to build Reicast](https://github.com/libretro/reicast-emulator#building-for-linux)
=> add reicast dependencies

Dockerfile
*adds missing `mkimg` tool needed by https://github.com/libretro/Lakka-LibreELEC/blob/master/scripts/image#L298
=> add missing mkimg via u-boot-tools

packages/libretro/dosbox-svn/package.mk
* Fixes issue building dosbox-svn mentioned by @bpereto in https://github.com/libretro/Lakka-LibreELEC/issues/556#issuecomment-449717489
=> Update PKG_SITE / PKG_GIT_URL for dosbox-svn #556

packages/libretro/dosbox-svn/package.mk
to avoid failure of nightly build (unknown revision) dosbox-svn bumped
to the most recent commit
=> update dosbox-svn (hotfix)

Dockerfile
Resolves `hexdump: not found`  issue encountered when building sameboy with [Dockerfile](https://github.com/libretro/Lakka-LibreELEC/blob/master/Dockerfile):
```
make[1]: Entering directory '/root/Lakka-LibreELEC/build.Lakka-Generic.x86_64-2.2-devel/sameboy-8f66f11/libretro'
echo "/* AUTO-GENERATED */" > ..//libretro/agb_boot.c
echo "/* AUTO-GENERATED */" > ..//libretro/cgb_boot.c
echo "const unsigned char agb_boot[] = {" >> ..//libretro/agb_boot.c
hexdump -v -e '/1 "0x%02x, "' ..//BootROMs/prebuilt/agb_boot.bin >> ..//libretro/agb_boot.c
echo "const unsigned char cgb_boot[] = {" >> ..//libretro/cgb_boot.c
/bin/sh: 1: hexdump: not found
hexdump -v -e '/1 "0x%02x, "' ..//BootROMs/prebuilt/cgb_boot.bin >> ..//libretro/cgb_boot.c
make[1]: *** [Makefile:322: ..//libretro/agb_boot.c] Error 127 …
```
=> add hexdump via bsdmainutils

Dockerfile, packages/libretro/reicast/package.mk, packages/libretro/reicast/patches/reicast-01-buildfix.patch
Removing Dockerfile updates which should be no longer needed and restore previous version of reicast patch, hopefully fixes #662
=> reicast: properly fix segfaults with Generic

config/options
Default behavior (i.e. `make image`) is to build for Generic.x86_64, `config/options` sets the TARGET_ARCH variable, but leaves ARCH empty. As some packages rely also on the ARCH variable, this sets the default (x86_64) value.
=> add default ARCH value

packages/libretro/picodrive/package.mk
compiles and runs full speed on switch
=> picodrive: add aarch64 support

scripts/get
Builds started with `NO_MIRROR=yes` will not try to download the targzs from the Lakka.tv mirrors, and always clone from git (if available).
=> Add NO_MIRROR to force cloning of git repos (disables targz download)

packages/libretro/snes9x/package.mk
The core has been rebased and commit id 2f6aee4 is no longer valid
=> snes9x: bump version to 68bf0fe

packages/libretro/citra/package.mk
better fixing the flags than copying over missing headers
=> citra: proper build fix

packages/linux-drivers/gamecon_gpio_rpi/README.md, packages/linux-drivers/gamecon_gpio_rpi/package.mk, projects/RPi/options, projects/RPi2/options
based on #470
[dnb]
If the original PR does not get rebased and corrected, this is the alternative.
=> RPi/RPi2: gamecon_gpio driver

scripts/get
removes original repo folder in case the remote has changed and makes a new clone of the new remote.
[dnb]
=> get-git: new clone when remote changes

pkg_all.sh
- drop some targets - only difference is uboot, enough to build for one
target from the group
- fix path of build folder - was not working with IGNORE_VERSION=1
[DNB] as no changes to build system/packages
=> pkg_all.sh: drop some targets

packages/libretro/retroarch/system.d/tmp-assets.mount, packages/libretro/retroarch/system.d/tmp-cores.mount, packages/libretro/retroarch/system.d/tmp-database.mount, packages/libretro/retroarch/system.d/tmp-joypads.mount, packages/libretro/retroarch/system.d/tmp-overlays.mount, packages/libretro/retroarch/system.d/tmp-shaders.mount
the mount units were not allways started before retroarch.service,
probably as original Before and WantedBy were both retroarch.target.
this should ensure that the overlays are mounted before retroarch
starts, otherwise retroarch starts without "seeing" any assets, cores,
etc in /tmp/...
=> Fix order of tmp mount units

packages/libretro/retroarch/system.d/tmp-assets.mount, packages/libretro/retroarch/system.d/tmp-cores.mount, packages/libretro/retroarch/system.d/tmp-database.mount, packages/libretro/retroarch/system.d/tmp-joypads.mount, packages/libretro/retroarch/system.d/tmp-overlays.mount, packages/libretro/retroarch/system.d/tmp-shaders.mount, packages/sysutils/systemd/package.mk
`systemd-tmpfiles-setup.service` was queued after `local-fs.target`, which
also mounted `/tmp` and in order to mount overlays, we need the workdir to
be created (by `systemd-tmpfiles-setup.service`), but `tmp.mount` (on which
the overlay `tmp-*.mount` units depend) is queued before `local-fs.target`.
this resulted into endless cycle and systemd broke the cycle by removing
one of the units, which resulted e.g. the worker dirs not to be ready or
skipping the `tmp-*.mount` units for overlays.
now `systemd-tmpfiles-setup.service` is queued after `tmp.mount` and
`var.mount` (instead of `local-fs.target`) and the queue is correct, the
overlays mount correctly.
=> systemd/retroarch overlays: fix systemd ordering

packages/libretro/retroarch-joypad-autoconfig/package.mk
includes udev config for 'Wireless Steam Controller'
=> retroarch-joypad-autoconfig: update to latest

build_all.sh
- use more build threads
more packages can be built concurrently when others are waiting for
their dependencies
- manipulate files only of the finished build
if other build job for other target was started outside of build_all, it
deleted files of that other target
=> build_all.sh changes

packages/libretro/ppsspp/package.mk, packages/libretro/retroarch/package.mk, packages/libretro/retroarch/system.d/tmp-system.mount, packages/libretro/retroarch/tmpfiles.d/retroarch-userdirs.conf
This adds a `system` directory overlay, with for now only the PPSSPP assets.
=> retroarch: add system overlay

packages/libretro/retroarch/package.mk, packages/libretro/retroarch/patches/nightly/retroarch-lakka_nightly_url.patch
if users try to upgrade nightly build, they are offered to upgrade to
latest stable release, which is a downgrade. a patch corrects the URL to
the nightlies server. this patch is applied only when the build is
started with LAKKA_NIGHTLY=yes, so it has no impact in other scenarios.
The nightlies build script will take care of populating the `.updater` folder with next nightly build.
=> Lakka: change online updater URL for nightlies

packages/libretro/tic80/package.mk
The change was merged forwards, so we can now update with that change in place. We'll continue to use our own remote though, in case there are any further modifications we want to rapidly push upstream:
https://github.com/libretro/TIC-80
=> tic80: update for disabled demo carts

scripts/get
this fixes failure when we switch a branch of a package and when the last used branch does not exist on the remote. also adds more output during the various git stages/actions.
=> get (git): fix fail when branch changes

distributions/Lakka/options
I left `LIBREELEC_VERSION` to `devel`, I will change it to `official` when building locally (along with `OFFICIAL=yes`), tell me if it's not the way to do it (should I set it to `2.3` too instead?)
=> Bump version to 2.3

packages/libretro/retroarch/package.mk
this protects the empty folder retroarch-system from being deleted by
the build script
[DNB] - do not build by buildbot
=> retroarch: add a .placeholder file

scripts/mkimage
on RPi4 it it seems the BOOT_IMAGE from kernel config file
(CONFIG_CMDLINE) is being ignored and updates are failing on missing
KERNEL or SYSTEM, as the update script defaults to "KERNEL" instead of
"kernel.img"
=> mkimage: add BOOT_IMAGE to cmdline.txt for RPi

build_all.sh
modification of the build script to start in dashboard mode. instead of
showing the output of the individual package compilation a dashboard is
shown showing the overall progress of the current build.
[DNB] do not build by buildbot (no changes to the packages/projects/etc.)
=> build_all.sh: start in dashboard mode

packages/libretro/quicknes/package.mk
This resolves this issue: https://github.com/libretro/Lakka-LibreELEC/issues/835
The package.mk file for quicknes assumed that the makefiles were in the libretro folder, but they are at the root. With this change, it actually builds the .so files and copies it correctly for quicknes.
=> quicknes: fix package.mk so it actually builds

packages/libretro/bsnes/package.mk
bsnes was rebased while I was building the 2.3.2 images
=> bsnes: update package

packages/security/libgpg-error/package.mk
This fixes issues with gawk v5.0.0, as described at:
https://dev.gnupg.org/T4459
=> Bump libgpg-error to v1.37

packages/libretro/theodore/package.mk
This new version of the Theodore core adds emulation of new Thomson computers (TO7 and TO7/70).
=> Update Theodore core

packages/libretro/mupen64plus_next/package.mk
I noticed it's setting `platform=unix`, possibly from before rpi4 had it's own config.
This works for me on RPi 4
=> Use rpi4 platform for mupen64plus next

packages/libretro/retroarch-joypad-autoconfig/package.mk, packages/linux/package.mk, packages/linux/patches/odroidgoA-4.4/linux-999-odroidgo2_joypad_v11.patch, packages/tools/u-boot/package.mk, projects/Rockchip/bootloader/mkimage, projects/Rockchip/bootloader/odroidgo2.ini, projects/Rockchip/devices/OdroidGoAdvance/options
This adds support for the OGA v1.1 (Black Edition)
* Bumps retroarch-joypad-autoconfig  to 7d6c1d4 (includes Oga v1.1 game-pad mapping)
* Bumps OGA Linux to 26e571d
* Bumps OGA u-boot to e7b255b
* Modified boot.ini to include dtbs for each revision
* Slight modification to the v1.0 game-pad mapping as I feel this gives more options (fast foward, load/save state, etc) please test to make sure its up to your liking. 
I did not include a rev 1.1 game-pad config as one already exists on the retroarch-joypad-autoconfig package and I am not sure how that is handled, but I think one should be created with all the hotkeys.
=> OdroidGoAdvance: Add support for OGA v1.1

packages/libretro/play/package.mk
play! has issues on aarch64/arm so let's only build it on i386/x86_64 for now
=> Only build play! on i386/x86_64

packages/libretro/snes9x2002/package.mk
The gain is not very big, hence it could explain why not activated...
I've seen some others distribution activating them.
Contra 3 has a slightly less choppy sound in gameplay on Pi 0, hence I only activated for this platform.
=> Enable asm optimization for snes9x2002 on rpi0/1 targets

packages/security/libgpg-error/package.mk
[dnb]
fixes build failure for Generic.i386 target
=> libgpg-error: add i386 support

packages/libretro/pcsx_rearmed/package.mk
Now by default lightrec is choose in pcsxrearmed but it's slower than ari64. This is confirmed on pi3 (30fps only with lightrec)
We can reactivate ari64 dynarec for ARM boards and keep lightrec for others.
=> Solve slow psxrearmed on rpi2 (and others arm boards)

distributions/Lakka/options, packages/libretro/emux-sms/package.mk
Needed to specify `PKG_TOOLCHAIN` but got it to build just fine.
=> fix and enable emux-sms build

distributions/Lakka/options
Built fine with RPi.ARM image.
Haven't done any performance testing with the core so leaving it enabled for everything.
=> Enable beetle-gba build

packages/devel/bison/package.mk, packages/devel/glib/package.mk, packages/devel/m4/package.mk, packages/devel/m4/patches/m4-1.4.18-glibc-change-work-around.patch, packages/libretro/retroarch/package.mk, packages/sysutils/e2fsprogs/package.mk, packages/sysutils/parted/patches/parted-sysmacros.patch, packages/sysutils/squashfs/patches/squashfs-tools-4.3-sysmacros.patch, packages/tools/populatefs/package.mk, packages/tools/populatefs/patches/populatefs-1.0-sysmacros.patch, packages/tools/qemu/package.mk, packages/tools/syslinux/patches/syslinux-6.03-sysmacros.patch, projects/Generic/options
These patches allow building Lakka on systems with glibc 2.28+
(ie. Fedora Linux)
Recent refactoring in glibc breaks assumptions built in gnulib and not updated yet software needs working around those assumptions.
=> Patches for glibc 2.28+ on Fedora

packages/libretro/retroarch/patches/retroarch-04-vc-egl.patch
Since we changed our retroarch version, we need to re-add the patch to fix RPi builds
=> Re-add vc-egl patch for RPi

packages/linux-firmware/brcmfmac_sdio-firmware/package.mk
Adds firmware and nvrams for BCM4329 used in Wandboard rev B1
=> brcmfmac_sdio-firmware: update to 4b4acd5

packages/lakka/RPi/package.mk, packages/linux-drivers/mk_arcade_joystick_rpi/Readme.md, packages/linux-drivers/mk_arcade_joystick_rpi/package.mk
Add mk_arcade_joystick_rpi kernel module
Based on game-hat package available in lakka 2.3.2
=> Add mk_arcade_joystick_rpi kernel module

packages/libretro/flycast/package.mk, projects/RPi/options
Flycast appears to already have a config for rpi4 aarch64, so this just configures `package.mk` to use it
ppsspp appears to build now and has an aarch64 config in its CMakeLists.txt.
=> rpi4-aarch64: fix flycast and enable ppsspp

packages/libretro/parallel-n64/package.mk, projects/RPi/options
I tried it and it works much better than mupen64.
=> rpi4-aarch64: add parallel-n64

packages/tools/bcm2835-bootloader/release
This ensures that it gets added and taken away as expected if a user upgrades from one to the other
=> rpi4-aarch64: set arm_64bit and kernel in distroconfig.txt

packages/libretro/mesen-s/package.mk, packages/libretro/mesen/package.mk
- As upstream [mesen](https://github.com/SourMesen/Mesen) and [mesen-s](https://github.com/SourMesen/Mesen-s) won't be updated anymore.
=> mesen: Switch to libretro repository

packages/devel/binutils/package.mk
Current version does not work with GCC 10 due to a missing include.
See: https://sourceware.org/pipermail/binutils/2019-June/107174.html
=> Bump binutils version

packages/compress/p7zip/patches/fix-int-cast-gcc10.patch
New GCC throws errors instead of warnings:
CPP/Common/MyWindows.h:89:43: error: narrowing conversion of
'-2147024809' from 'LONG' {aka 'int'} to 'unsigned int' [-Wnarrowing]
=> Adds a fix for p7zip on GCC10

projects/NXP/devices/iMX6/patches/linux/linux-002-imx6qdl-wandboard-dtb-i2c-bus-recovery.patch
In Wandboard scl/sda are stuck low during transfer sometimes, this can happen while reading EDID from TV and lead to no sound. Add scl/sda gpios defitions to device tree to apply i2c bus recovery.
=> NXP/iMX6: add fix Wandboard device tree for i2c bus recovery

packages/linux/package.mk
Previously tried to look at PLATFORM which isn't set.
I decided to check PROJECT as well because we're specifically copying broadcom files here, and we might want aarch64 for other RPis.
Also swapped the order as this is the 'special' case and it makes sense (to me at least) to have the default 'else' case as the previous behaviour.
=> linux: Copy from dts/broadcom/*.dtb when PROJECT=RPi and ARCH=aarch64

packages/devel/binutils/package.mk
Cannot rollback to previous version since it does not build with gcc 9/10
However this version seems to work with gcc 10 *and* also produce valid binutils
that are not affected by the ABI change (see https://lkml.org/lkml/2020/1/30/1005)
=> Downgrade binutils to fix build errors

projects/NXP/devices/iMX6/filesystem/usr/lib/udev/rules.d/80-wandboard-bluetooth-firmware.rules, projects/NXP/devices/iMX6/linux/linux.arm.conf, projects/NXP/devices/iMX6/patches/linux/linux-004-imx6qdl-wandboard-revc1-dtb.patch
- remove hciattach service start for BCM4330 from udev rule
- configure HCI UART driver as module, enable Broadcom protocol
- add BCM4330 bluetooth node to Wandboard c1 device tree
=> NXP/iMX6: use HCI UART driver for BCM4330 in Wandboard C1

packages/graphics/librga/package.mk
Seems like default branch changed and it can't fetch the commit otherwise?
=> Fix librga git clone

distributions/Lakka/options
melonds will be added to build plan for all targets, so does mesa.
and the targets which don't use mesa will not config mesa correctly.
thus build failed.
Signed-off-by: Zhang Ning <832666+zhangn1985@users.noreply.github.com>
=> filter out melonds

packages/linux-firmware/brcmfmac_sdio-firmware-imx/package.mk, packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk, packages/linux-firmware/brcmfmac_sdio-firmware/package.mk, packages/linux-firmware/dvb-firmware/package.mk, packages/linux-firmware/firmware-dragonboard/package.mk, packages/linux-firmware/firmware-imx/package.mk, packages/linux-firmware/firmware-realtek/package.mk, packages/linux-firmware/iwlwifi-firmware/package.mk, packages/linux-firmware/kernel-firmware/package.mk, packages/linux-firmware/meson-firmware/package.mk, packages/linux-firmware/misc-firmware/package.mk, packages/linux-firmware/rockchip-firmware/package.mk, packages/linux-firmware/wlan-firmware/package.mk
This uses the locking mechanism provided by the build system to grab a lock
(namely firmware-install) every time a firmware needs to be installed.
This is similar to the mechanism that python uses (exec_thread_safe)
but less restrictive since we do not grab a global lock.
=> Add kernel install locks to prevent race conditions

packages/libretro/duckstation/package.mk
> 2020/11/21: AArch32/armv7 recompiler added. Android and Linux builds will follow after further testing, but for now you can build it yourself.
[Source](https://github.com/stenzek/duckstation#latest-news)
=> duckstation : Enable arm platform and update to latest version

packages/tools/u-boot/package.mk
These are minor changes that are not really needed right now, but it will help reduce conflicts in future upgrades.
Original commints: LibreELEC/LibreELEC.tv@e868c551ba6b591ab0e12f559e1a4a487d29902f and LibreELEC/LibreELEC.tv@a574e016d0f7fe42550b8d04b45da7d47ba95aa5
=> u-boot: add UBOOT_TARGET

projects/Generic/patches/linux/linux-777-Makefile-build-firmware-built-in-arg-list-squeeze.patch
Patch: Temporary workaround for 'Argument list too long'
error with kernel-firmware above 20190514.
=> Generic: linux: fix 'Argument list too long' for built-in firmware

packages/linux/patches/odroidgoA-4.4/linux-990-rg351p-rumble.patch, packages/linux/patches/odroidgoA-4.4/linux-998-rg351p-dts.patch
This is a bit of a hardcore workaround, but it is actually simpler than adding proper support for PWM rumble in Retroarch.
I tested it thoroughly on my RG351P, in particular the USB reconnect, which is hard to get right.
=> Adding Kernel driver for RG351P gamepad + rumble, as a patch.

projects/Allwinner/devices/H6/patches/linux/21-pineh64-model-b-wifi-bt.patch, scripts/uboot_helper
This was originally proposed in PR https://github.com/libretro/Lakka-LibreELEC/pull/1010 but closed at the time due to missing device support in Linux 5.4 version. Now Lakka has been updated to Linux 5.9 version which does have support for this device.
=> Add support for PineH64 Model B

packages/addons/addon-depends/chrome-depends/icu/package.mk, packages/devel/liblcf/patches/liblcf-02-add-icu-compile-defs.patch
Fixes #1141 
Add the missing ICU shared libraries and fixed the following bug:
ICU can be compiled with or without symbol renaming support. Apps need to consider this by including a switch in the compiler options. This information is stored in the icu pkgconfig file. Libclf does not check for this and assumes that symbol renaming is enabled. In the case of Lakka it is disabled though, leading to a runtime error where the libicu.so* symbols cannot be found due to a naming mismatch.
=> Fix easyrpg core runtime error (missing icu4c libraries)

packages/libretro/melonds/package.mk
Referenced commit id `289d544` does not exist in https://github.com/libretro/melonds, updated to `b8e1eca`
=> melonds: fix commit id

config/functions, scripts/build, scripts/install
cp (and potentially mkdir -p) are not atomic, and we have seen situations where two packages
concurrently copying the same file (eg. the udev rule for xf86-video-nvidia and
xf86-video-nvidia-legacy) will succeed for one package but the other package fails with
a "file exists" error (as the file didn't exist when it checked, but does exist when it
actually copies the file). Not even cp -f will avoid this issue.
There are several workarounds, but the most practical (and general) solution is to ensure
sequential updates of the image and shared sysroot directories.
This is part of PR 4092 from LE upstream.
=> buildsystem: use an update lock when updating image and sysroot

create_libretro_tarballs.sh, get_libretro_tarball.sh
two new tools:
create_libretro_tarballs.sh: creates a tarball of already existing
folder with cloned repository for future re-use
get_libretro_tarball.sh: retrieves a tarball from a mirror in case a
specific version cannot be checked-out by the buildsystem
create_libretro_tarballs.sh should be run by the mainteners on regular
basis, so there are backups of most versions of used libretro
packages/cores
get_libretro_tarball.sh should be run by a builder in case the build
errors due to non-existent hash in cloned repository
=> create / get libretro tarball

packages/debug/gdb/package.mk
It's very handy when debugging assembly code (layout asm)
=> Enable gdb's TUI

packages/security/nss/patches/nss-fix-ftbfs-glibc-invalid-oob-error.patch
This is an upstream issue that cannot be fixed yet, and this is the
proposed mitigation for NSS in the meantime.
=> Fix issues with newer gcc

packages/libretro/lutro/package.mk
Didn't do a fresh build on lutro and found a compile issue for `ARM` when NEON is enabled.
=> lutro: export HAVE_NEON to fix build

scripts/uboot_helper
Official OGAs are all included in the odroidgo2 target (and DTB is
selected via boot.ini and u-boot cooperation).
=> Remove unnecessary v11 target

packages/addons/addon-depends/chrome-depends/icu/package.mk, packages/addons/addon-depends/chrome-depends/icu/patches/icu-01_ldflags.patch
The previous icu package built an empty libicudata.so library and was missing a patch from upstream LibreELEC that fixes a runtime error on some platforms. This should fix #1189.
=> Fix missing icudata library and runtime error

packages/linux/patches/odroidgoA-4.4/linux-998-rg351v-dts.patch, projects/Rockchip/devices/OdroidGoAdvance/options, scripts/image
This adds a new function hook that can be defined for devices that have
slightly different cmdline within the same configuration.
Remove vcchost regulator since it is not used and just makes the rumble
go crazy during kernel boot.
=> Fix console rotation on OGA family and rumble on boot too

packages/graphics/mesa/package.mk
- replace deprecated 'true/false' with 'enabled/disabled'
See: https://github.com/mesa3d/mesa/commit/138c003d22739b0d1e6860ed398dd511a44cde04
- remove 'asm' option
See: https://github.com/mesa3d/mesa/commit/20294dceebc23236e33b22578245f7e6f41b6997
- remove unnecessary condition for i386 after #1162
=> mesa: fix options

packages/libretro/genesis_plus_gx_wide/package.mk
It was overwritting in some cases the wrong .so file. This enables both
emulators to be built
=> Fix Genesis Wide .so filename

packages/sysutils/pciutils/package.mk
This was recently enabled for all architectures but only gets installed for x86. Let's install it everywhere.
Main motivation: flashing rpi-eeprom
=> Install pci-utils everywhere

packages/python/utils/python-raspberry-gpio/package.mk, projects/RPi/options
Following my feature request #1227 , after some tests is proves nearly impossible to have pip in Lakka. The efforts required to make it work makes adding python packages on a per-user basis easier. However RPi.GPIO is still a vital  package as it allows a lot of stuff, including safe shutdown scripts for cases with power buttons. While there are a lot of precompiled RPi.GPIO floating around, these only account for arm compilations, not aarch64. For such a core Pi Python component, I feel like having it compile with Lakka would be a benefit.
I've forked and am working on a safe shutdown script that could serve as the basis for multiple cases for Lakka users (mine is for Retroflag's but it would be easy to fork and adapt it).
Fix #1227
RPi.GPIO package upgraded to SPDX format. Being unsure …
=> Added the RPi.GPIO Python library to the RPi Project

packages/libretro/retroarch/patches/retroarch-99-eject_disc.patch, packages/libretro/retroarch/patches/retroarch-99-timezones.patch
fixes #1261 and https://github.com/libretro/RetroArch/issues/5183
adds new entry (where the entries for dumping CD is) to eject the disc - in case the CD drive has no physical button to eject the disc / the button does not work
adds new entry to Services sub-menu of Settings (where other Lakka specific settings are - enable/disable Samba/SSH/...) and allows the user to set the time zone from the GUI without needing access to the command line / file system
=> retroarch: eject + timezone patch

build_all.sh, distributions/Lakka/options
It doesn't build with the latest mesa. It can be re-enabled once it's either fixed or mesa is updated
=> rpi4: disable openlara

packages/libretro/retroarch/package.mk
RA is rotated 90 CCW. Rotate 270 to fix in all the cores.
This doesn't fix RA Menus as that requires a solution to https://github.com/libretro/RetroArch/issues/6770.
=> Rotate cores on GPiCase

projects/RPi/devices/GPICase/options
Audio uses legacy path through Broadcom fw so enable it with cmdline.
=> GPiCase: add extra cmdline args needed for audio

packages/tools/joycond/package.mk
When the original package was added, it was based off of a non working version of the package.mk, fix the issues, so the service can actually start.
=> Fix joycond package, so it can actually start on bootup

packages/graphics/bcm2835-driver/package.mk
This is what my previous PR was trying to solve. It gets files from the same package, but we fetch it from libreelec currently meaning we're limited in which commits we can pin to.
This change just fetches the exact same package and the exact same version as bcm2835-bootloader (https://github.com/libretro/Lakka-LibreELEC/blob/master/packages/tools/bcm2835-bootloader/package.mk#L6). In the future we can merge them.
=> rpi: make bcm2835-driver use the same version as bcm2835-bootloader

build_all.sh, packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk, packages/libretro/retroarch/package.mk
- retroarch: add VULKAN only when have VULKAN_SUPPORT
- mpg123: build with PIC for all targets
=> fix build for 32-bit Generic

build_all.sh, packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk, packages/libretro/retroarch/package.mk
- retroarch: add VULKAN only when have VULKAN_SUPPORT
- mpg123: build with PIC for all targets
backport of #1317
=> [LakkaV3] fix build for 32-bit Generic

distributions/Lakka/options, packages/libretro/beetle-saturn/package.mk
was removed due to size constraints of the parition. as the partition
size was increased, the core can be included again.
backport of #1320
=> beetle-saturn: update and add the core back to list

packages/sysutils/systemd/package.mk
Try suggested fix for https://github.com/libretro/Lakka-LibreELEC/issues/1174
I don't have a switch to test this with but it doesn't seem like a dangerous change.
=> rpi: change HandlePowerKey action to poweroff

packages/graphics/bcm2835-driver/package.mk
To match kernel and bcm2835-bootloader
=> rpi: bump bcm2835-driver to 5.10.39 too

packages/libretro/swanstation/package.mk, packages/libretro/swanstation/patches/no_opengl/swanstation-01-default_sw_renderer.patch
This patch makes SwanStation to compile with default  GPU renderer set to Software, so it can be started on platforms without OpenGL support. For platforms with OpenGL support this patch is reversed during post-patch.
=> swantstation: default to sw renderer when no OGL

packages/libretro/retroarch/package.mk
See https://github.com/libretro/RetroArch/pull/11181
This is UNTESTED, so feel free to close and consider it as advisory :) I don't have a lakka dev environment/spare SD. Just something I was meaning to eventually do after above PR was merged. It's only really relevant for things like swanstation that actually use the API to determine GLES version support. see https://github.com/stenzek/duckstation/issues/694. You can see if it's working via the presence of GLES 3.x items in a verbose log (regardless of what core retroarch is running).
I don't know if any of these other devices need updating. I imagine a few are gles3.x
=> retroarch: build with gles 3 minor version support [WIP]

projects/Generic/linux/linux.i386.conf, projects/Generic/linux/linux.x86_64.conf
=> linux: Enable CONFIG_BLK_DEV_DM on Generic

packages/linux-firmware/brcmfmac_sdio-firmware/package.mk
Nvram files for BCM4330 used in CuBox-i added since LibreELEC/brcmfmac_sdio-firmware@6d49ff1.
This update shoud fix #1403.
buildbot: [dnb]
=> brcmfmac_sdio-firmware: update to 3ddc301

packages/libretro/retroarch/patches/retroarch-07-revert_resampler_changes.patch
Still sound noisy after savestave loading on iMX6.
Patch modified after libretro/RetroArch@3f00d2f041abcd444f0472e7b05ee87ff107c948.
=> retroarch: revert resampler changes (patch)

projects/RPi/devices/RPi4/config/distroconfig.txt
It was done here: https://github.com/libretro/Lakka-LibreELEC/commit/58dafbe511f79172468bed305b0d2b267f9127d5
but that might get overwritten with this version
=> rpi4: disable 4k output on upgrades too

packages/devel/libaio/package.mk
- It will be needed to enable pcsx2 core.
=> libaio : Add libaio.so to sysroot and install

libretro_update.sh, packages/libretro/duckstation/package.mk
to have reproducible builds, we need to use the same version of the core, which cannot be guaranteed when downloading the core from upstream at build time. on the Lakka mirror server we will keep various versions of the binary core so we can re-download that specific version of the core at build time.
=> duckstation: use specific version of the binary core

packages/libretro/swanstation/package.mk
Fix compilation issue
[Source](https://github.com/kivutar/swanstation/tags)
=> swanstation: Keep date as package version

packages/libretro/mupen64plus_next/package.mk
This means we don't have to edit it for other possibly upcoming targets
=> mupen64plus-nx: add wildcard to catch all rpi4 variants

packages/graphics/bcm2835-driver/package.mk, packages/linux/package.mk, packages/linux/patches/rpi/linux-add_support_for_non-standard_modes_in_vec.patch, packages/tools/bcm2835-bootloader/package.mk
kernel/firmware updated to latest release
added patch to allow non-standard modes in VEC (#1290)
=> Update RPi kernel/firmware + add support for non-standard modes in VEC

packages/graphics/bcm2835-driver/package.mk, packages/tools/rpi_userland/package.mk, projects/RPi/options
solves incompatibility on aarch64 targets with binaries provided by
bcm2835-driver for 32-bit ARM.
fixes #1496
=> RPi: build GPU tools

packages/tools/u-boot/package.mk, packages/tools/u-boot/patches/odroidgoadvance/0001-Kbuild-fix-escaping-in-.cmd-files-for-future-Make.patch, packages/tools/u-boot/patches/odroidgoadvance/0002-kbuild-fix-escaping-in-appending-U-Boot-own-DT.patch
This should be backwards compatible with other make versions AFAIK
=> Add u-boot fixes for OGA fork

packages/tools/xbox360-controllers-shutdown/package.mk, packages/tools/xbox360-controllers-shutdown/system.d/xbox360-controllers-shutdown.service
Added xbox360-controllers-shutdown package, a small utility to automatically turn off all connected Xbox360 wireless controllers on system shutdown.
=> Added xbox360-controllers-shutdown package

packages/libretro/libretro-database/package.mk
This updates libretro-database to the latest. Looks like there was a file that fails to check out on the current commit, so updating should fix it.
=> libretro-database: Update to the latest RDB files

packages/libretro/play/package.mk
The updated version of Play! requires CMake version 3.15, which is not yet available on our infrastructure. This change rolls back to the previous version of Play!.
=> libretro: play: Rollback for older CMake

packages/libretro/mame2003-plus/package.mk
This updates the mame2003-plus core to the latest as investigation on TickerBoard failing on #1577.
=> libretro: mame2003-plus: Update to the latest

packages/sysutils/ntfs-3g_ntfsprogs/package.mk
It's moved to github: https://jp-andre.pagesperso-orange.fr/advanced-ntfs-3g.html
LibreELEC have removed it (https://github.com/LibreELEC/LibreELEC.tv/commit/f6e648aad8c5725f22a60fd6ffded6e7cdd33566) possibly because there's a kernel implementation in 5.15 but we're on 5.10
=> ntfs-3g_ntfsprogs: fix download location

packages/libretro/tic80/package.mk
Moves the `PKG_CMAKE_SCRIPT` and `PKG_CMAKE_OPTS_TARGET` definitions to `configure_package()`.
Thank you to @gouchi for the tip.
=> tic80: Use configure_package()

packages/libretro/citra/package.mk
This updates to the latest version of Citra, at https://github.com/libretro/citra/commit/0a837dbfcf0a435eb05b2bef5ad5b05210fbcc80 .
=> citra: Update to latest version of Citra

packages/libretro/retroarch/package.mk, packages/multimedia/ffmpeg/package.mk, packages/multimedia/libx264/package.mk
This is untested by me in 3.x, but the same patch works in 4.x, I just rebased it on 3.x tree, so it would get into a pr build, so it can be tested on other boards.
=> Fix retroarch recording/streaming In Lakka 3.x
